model:
    seq2vec:
        arch: skipthoughts
        dir_st: /home/mcx/RS/KAMCL-main/data
        type: BayesianUniSkip
        dropout: 0.25
        fixed_emb: False
    embed:
        embed_dim: 512
    name: KAMCL
dataset:
    datatype: rsitmd
    data_split:
    data_path: '/home/mcx/RS/KAMCL-main/data/rsitmd_precomp/'
    image_path: '/home/mcx/RS/Datasets/RSITMD/images/'
    vocab_path: '/home/mcx/RS/KAMCL-main/vocab/rsitmd_splits_vocab.json'
    tag_path: '/home/mcx/RS/KAMCL-main/data/rsitmd_precomp/tags_label_th_1.txt'
    tag_vocab: '/home/mcx/RS/KAMCL-main/data/rsitmd_precomp/tags_label_th_1/tag_vocab_512.json'
    batch_size: 100
    batch_size_val: 100
    workers: 4
optim:
    epochs: 30
    lr: 0.0002
    lr_decay_param: 0.7
    lr_update_epoch: 10
    grad_clip: 0
    max_violation: 0
    margin: 0.2
    resume: False
logs:
    eval_step: 1
    print_freq: 10
    ckpt_save_path: "/home/mcx/RS/KAMCL-main/checkpoint/"
    logger_name: 'logs/'
k_fold:
    experiment_name: 'rsitmd_KAMCL'
    nums: 10
    current_num: 0
